# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-SWF-Editor
version:      0.04_01
version_from: lib/IO/SWF/Editor.pm
installdirs:  site
requires:
    Image::Magick:                 6.6.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
