---
abstract: 'Parse and edit SWF binary by Perl.'
author:
  - 'Seiji Harada <liptontea2k@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-SWF-Editor
no_index:
  directory:
    - t
    - inc
requires:
  Image::Magick: 0
version: 0.01
